# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_sth.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_objects_add(object):
    def setupUi(self, objects_add):
        objects_add.setObjectName("objects_add")
        objects_add.resize(568, 317)
        self.name_3 = QtWidgets.QLabel(objects_add)
        self.name_3.setGeometry(QtCore.QRect(30, 30, 101, 21))
        self.name_3.setObjectName("name_3")
        self.name_4 = QtWidgets.QLabel(objects_add)
        self.name_4.setGeometry(QtCore.QRect(30, 130, 101, 21))
        self.name_4.setObjectName("name_4")
        self.add_2 = QtWidgets.QPushButton(objects_add)
        self.add_2.setGeometry(QtCore.QRect(390, 250, 93, 41))
        self.add_2.setObjectName("add_2")
        self.name = QtWidgets.QLineEdit(objects_add)
        self.name.setGeometry(QtCore.QRect(30, 80, 141, 22))
        self.name.setObjectName("name")
        self.analogue = QtWidgets.QLineEdit(objects_add)
        self.analogue.setGeometry(QtCore.QRect(30, 180, 141, 22))
        self.analogue.setObjectName("analogue")
        self.labelnameN_2 = QtWidgets.QLabel(objects_add)
        self.labelnameN_2.setGeometry(QtCore.QRect(200, 40, 51, 31))
        self.labelnameN_2.setObjectName("labelnameN_2")
        self.price_n = QtWidgets.QLineEdit(objects_add)
        self.price_n.setGeometry(QtCore.QRect(200, 80, 71, 22))
        self.price_n.setObjectName("price_n")
        self.labelnameN_3 = QtWidgets.QLabel(objects_add)
        self.labelnameN_3.setGeometry(QtCore.QRect(310, 40, 51, 31))
        self.labelnameN_3.setObjectName("labelnameN_3")
        self.labelnameN_4 = QtWidgets.QLabel(objects_add)
        self.labelnameN_4.setGeometry(QtCore.QRect(320, 140, 51, 31))
        self.labelnameN_4.setObjectName("labelnameN_4")
        self.price_a = QtWidgets.QLineEdit(objects_add)
        self.price_a.setGeometry(QtCore.QRect(200, 180, 71, 22))
        self.price_a.setObjectName("price_a")
        self.labelnameN_5 = QtWidgets.QLabel(objects_add)
        self.labelnameN_5.setGeometry(QtCore.QRect(200, 140, 51, 31))
        self.labelnameN_5.setObjectName("labelnameN_5")
        self.structure_a = QtWidgets.QPlainTextEdit(objects_add)
        self.structure_a.setGeometry(QtCore.QRect(300, 180, 221, 41))
        self.structure_a.setObjectName("structure_a")
        self.structure_n = QtWidgets.QPlainTextEdit(objects_add)
        self.structure_n.setGeometry(QtCore.QRect(300, 80, 221, 41))
        self.structure_n.setObjectName("structure_n")
        self.add_picture = QtWidgets.QPushButton(objects_add)
        self.add_picture.setGeometry(QtCore.QRect(30, 230, 151, 28))
        self.add_picture.setObjectName("add_picture")

        self.retranslateUi(objects_add)
        QtCore.QMetaObject.connectSlotsByName(objects_add)

    def retranslateUi(self, objects_add):
        _translate = QtCore.QCoreApplication.translate
        objects_add.setWindowTitle(_translate("objects_add", "Form"))
        self.name_3.setText(_translate("objects_add", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Название</span></p></body></html>"))
        self.name_4.setText(_translate("objects_add", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Похожий</span></p></body></html>"))
        self.add_2.setText(_translate("objects_add", "Добавить"))
        self.labelnameN_2.setText(_translate("objects_add", "Цена"))
        self.labelnameN_3.setText(_translate("objects_add", "Состав"))
        self.labelnameN_4.setText(_translate("objects_add", "Состав"))
        self.labelnameN_5.setText(_translate("objects_add", "Цена"))
        self.add_picture.setText(_translate("objects_add", "Добавить фотографию"))
