# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(645, 450)
        MainWindow.setMinimumSize(QtCore.QSize(500, 450))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.search = QtWidgets.QLineEdit(self.centralwidget)
        self.search.setGeometry(QtCore.QRect(20, 20, 401, 22))
        self.search.setObjectName("search")
        self.pushButtonSearch = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSearch.setGeometry(QtCore.QRect(440, 16, 131, 28))
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.labelname = QtWidgets.QLabel(self.centralwidget)
        self.labelname.setGeometry(QtCore.QRect(20, 140, 131, 31))
        self.labelname.setObjectName("labelname")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(20, 90, 101, 21))
        self.name.setObjectName("name")
        self.labelnameN = QtWidgets.QLabel(self.centralwidget)
        self.labelnameN.setGeometry(QtCore.QRect(160, 130, 151, 51))
        self.labelnameN.setObjectName("labelnameN")
        self.similar_name = QtWidgets.QLabel(self.centralwidget)
        self.similar_name.setGeometry(QtCore.QRect(20, 60, 371, 21))
        self.similar_name.setMouseTracking(True)
        self.similar_name.setObjectName("similar_name")
        self.popular_lable = QtWidgets.QLabel(self.centralwidget)
        self.popular_lable.setGeometry(QtCore.QRect(20, 220, 121, 21))
        self.popular_lable.setObjectName("popular_lable")
        self.prise_value = QtWidgets.QPushButton(self.centralwidget)
        self.prise_value.setGeometry(QtCore.QRect(340, 100, 101, 28))
        self.prise_value.setObjectName("prise_value")
        self.popular = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.popular.setGeometry(QtCore.QRect(20, 260, 261, 151))
        self.popular.setObjectName("popular")
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(390, 260, 161, 51))
        self.add.setObjectName("add")
        self.name_2 = QtWidgets.QLabel(self.centralwidget)
        self.name_2.setGeometry(QtCore.QRect(170, 90, 101, 21))
        self.name_2.setObjectName("name_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 645, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.recent_action = QtWidgets.QAction(MainWindow)
        self.recent_action.setObjectName("recent_action")
        self.favorite_action = QtWidgets.QAction(MainWindow)
        self.favorite_action.setObjectName("favorite_action")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonSearch.setText(_translate("MainWindow", "Искать продукты"))
        self.labelname.setText(_translate("MainWindow", "Тут будет название"))
        self.name.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Назавание</span></p></body></html>"))
        self.labelnameN.setText(_translate("MainWindow", "Тут будут похожие"))
        self.similar_name.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.popular_lable.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Популярные</span></p></body></html>"))
        self.prise_value.setText(_translate("MainWindow", "Подробнее"))
        self.add.setText(_translate("MainWindow", "Добавить"))
        self.name_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Похожие</span></p></body></html>"))
        self.action.setText(_translate("MainWindow", "Регион"))
        self.action_2.setText(_translate("MainWindow", "Каталог"))
        self.recent_action.setText(_translate("MainWindow", "Недавние"))
        self.favorite_action.setText(_translate("MainWindow", "Любимые"))
